version: "3.7"

services:
    postgres:
        image: bitnami/postgresql:latest
        ports:
            - "3543:5432"
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=employee
        volumes:
            - employee_pg_data:/bitnami/postgresql

    redis:
        image: bitnami/redis:latest
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "3637:6379"
        volumes:
            - employee_redis_data:/bitnami/redis/data

volumes:
    employee_pg_data:
    employee_redis_data:
