import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
		<Header />
	  	<main className="grid grid-cols-12 min-h-screen flex-col items-start justify-start p-5">
			<div className="col-span-10 col-start-2 bg-white rounded-md h-full">
				{children}
			</div>
		</main>
	  </body>
    </html>
  );
}
